spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fin
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: passw0rd
  sql:
    init:
      mode: always
      schema-locations: classpath:data.sql

logging:
  level:
    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
